server.port=8081
spring.data.mongodb.uri=mongodb://localhost:27017/Cluster1
spring.data.mongodb.auto-index-creation=true
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=compilers-group
spring.kafka.consumer.auto-offset-reset=earliest
